services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "C0mplexW@chtw00rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/1433"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mssqldata:/var/opt/mssql

  web:
    build:
      context: ./Server
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Hospital=Server=localhost,1433;Database=Hospital;User=sa;Password=C0mplexW@chtw00rd;TrustServerCertificate=True;Encrypt=True
    # Do not publish backend directly; proxy will route /api to this service
  carsclient:
    build:
      context: ./Client
      dockerfile: Dockerfile
    depends_on:
      - web
    # Do not publish frontend directly; proxy will serve the frontend on host port 80
    restart: unless-stopped
  proxy:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      web:
        condition: service_started
      carsclient:
        condition: service_started
    restart: unless-stopped
volumes:
  mssqldata:
